config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  patch 'posts/edit', to: 'posts#update'
  get 'posts/destroy'
  post 'posts/new', to: 'posts#create'
  post 'posts/store'
  get 'posts/search', to: 'posts#search_post'
  get 'posts/export', to: 'posts#export_csv'
  post 'posts/import', to: 'posts#import_csv'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'users/list', to: 'users#index'
  get 'users/new'
  post 'users/new', to: 'users#create'
  get 'users/search', to: 'users#search_user'
  get 'users/show'
  get 'users/destroy'
  get 'users/edit'
  patch 'users/edit', to: 'users#update'

  get 'users/profile'
  get 'users/editPassword'
  patch 'users/editPassword', to: 'users#updatePassword'
  get 'users/editProfile'
  patch 'users/editProfile', to: 'users#updateProfile'

  get 'password/reset'
  post 'password/reset' , to: 'password#create'
  get 'password/reset/edit', to: 'password#edit'
  patch 'password/reset/edit' , to: 'password#update'

  get 'login', to: 'login#login'
  post 'login', to: 'login#attempt_login'
  get 'logout', to: 'login#logout'
  
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
    def reset
        
    end

    def create
        run User::Operation::SendEmail
        @user = result[:user]
        if @user
            PasswordMailer.with(user:@user).reset.deliver_now
            redirect_to password_reset_path, :notice => "Email sent with password reset instructions."
        else
            redirect_to password_reset_path,notice:"We did not find this email."
        end
    end

    def edit
        @user = User.find_signed!(params[:token], purpose:"password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to login_path, notice:"Your token has expired.Please try again."
    end

    def update
        @userP = User.find_signed!(params[:token], purpose:"password_reset")
        if params[:user]
            params[:id] = params[:user][:id]
        else
            params[:user] = params[:user_contract_update_password]
            params[:id] = params[:user][:id]
        end
        _ctx = run User::Operation::UpdatePassword do |result| 
            return redirect_to password_reset_path, alert:"Your password was reset successfully.Please sign in."
        end
        @user   = _ctx["contract.default"]
        @password  = "Editing #{_ctx[:model].password}"
        @password_confirmation  = "Editing #{_ctx[:model].password_confirmation}"
        render :edit
    end
end

app/views/password/edit.html.slim
.form 
    .form-content 
        h2 Reset your password
        .warning-message
            = flash.notice
        = form_with model: @user, url: password_reset_edit_path(token:params[:token]) do |f|
            .content
                = f.hidden_field 'id'
                label Password
                span class="required-sign" * 
                = f.password_field 'password'
                - if @user.errors[:password].any?
                    .warning-message This #{ @user.errors[:password][0]}
            .content
                label Password Confirm
                span class="required-sign" * 
                = f.password_field 'password_confirmation'
                - if @user.errors[:password_confirmation].any?
                    .warning-message This #{ @user.errors[:password_confirmation][0]}
            .button-group
                = link_to "Back", password_reset_path, class: 'sub-btn'
                = f.submit 'Reset Password', class: 'sub-btn reset-link-btn'

app/views/password/reset.html.slim
.form 
    .form-content 
        h2 Reset Password
        .successMessage
            = flash.alert
        .warning-message
            = flash.notice
        = form_with model: @user, url: password_reset_path do |f|
            .content
                label Email
                span class="required-sign" * 
                = f.text_field 'email'
            .button-group
                = link_to "Back", login_path, class: 'sub-btn'
                = f.submit 'Send', class: 'sub-btn'