config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  patch 'posts/edit', to: 'posts#update'
  get 'posts/destroy'
  post 'posts/new', to: 'posts#create'
  post 'posts/store'
  get 'posts/search', to: 'posts#search_post'
  get 'posts/export', to: 'posts#export_csv'
  post 'posts/import', to: 'posts#import_csv'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'users/list', to: 'users#index'
  get 'users/new'
  post 'users/new', to: 'users#create'
  get 'users/search', to: 'users#search_user'
  get 'users/show'
  get 'users/destroy'
  get 'users/edit'
  patch 'users/edit', to: 'users#update'

  get 'users/profile'
  get 'users/editPassword'
  patch 'users/editPassword', to: 'users#updatePassword'
  get 'users/editProfile'
  patch 'users/editProfile', to: 'users#updateProfile'

  get 'password/reset'
  post 'password/reset' , to: 'password#create'
  get 'password/reset/edit', to: 'password#edit'
  patch 'password/reset/edit' , to: 'password#update'

  get 'login', to: 'login#login'
  post 'login', to: 'login#attempt_login'
  get 'logout', to: 'login#logout'
  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    # validates :name, presence: true ,length: { maximum: 255 }
    # validates :email, presence: true ,length: { maximum: 255 } ,format: { with: URI::MailTo::EMAIL_REGEXP }
    # validates :password, presence: true, confirmation: true ,length: { within: 4..255 }
    # validates :password_confirmation, presence: true,length: { within: 4..255 }
    # validates :phone, length: { maximum: 12 }
    # validates :role, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:resetPassword]
  
  def index
    run User::Operation::Index do |result|
      @users = result[:users].paginate(:page=>params[:page] , per_page: 5)
    end
  end

  def new
    @form = User.new
  end

  def show
    run User::Operation::Edit
    @user = result["model"]
  end

  def edit
    run User::Operation::Edit
    @user = result["model"]
  end

  def create
    run User::Operation::Create do |result|
      return redirect_to users_list_path,notice: "User is saved successfully!"
    end
    render :new
  end

  def search_user
    @searchKey = params[:searchInfo]
    run User::Operation::Search do |result|
      @users = result[:users].paginate(:page=>params[:page],per_page: 5)
      render :index
      return
    end
  end

  def update
    if params[:user]
      puts (params[:user])
    else 
      params[:user] = params[:user_contract_update]
    end
    _ctx = run User::Operation::Update do |result| 
      return redirect_to users_show_path('id'=>params[:user][:id]), notice: "User updated successfully!"
    end
    @user   = _ctx["contract.default"] 
    @name  = "Editing #{_ctx[:model].name}"
    @email  = "Editing #{_ctx[:model].email}"
    @phone  = "Editing #{_ctx[:model].phone}"
    render :edit
  end

  def destroy 
    run User::Operation::Destroy do |_|
      return redirect_to users_list_path, notice: "User deleted successfully!"
    end  
  end

  def profile
    run User::Operation::Edit
    @user = result["model"]
  end

  def editPassword
    run User::Operation::Edit
    @user = result["model"]
  end

  def editProfile
    run User::Operation::Edit
    @user = result["model"]
  end

  def updatePassword
    if params[:user]
      puts (params[:user])
    else 
      params[:user] = params[:user_contract_update_password]
    end
    _ctx = run User::Operation::UpdatePassword do |result| 
      return redirect_to users_profile_path('id'=>params[:user][:id]), notice: "Password updated successfully!"
    end
    @user   = _ctx["contract.default"] 
    @password  = "Editing #{_ctx[:model].password}"
    @password_confirmation  = "Editing #{_ctx[:model].password_confirmation}"
    render :editPassword
  end

  def updateProfile
    if params[:user]
      puts (params[:user])
    else 
      params[:user] = params[:user_contract_update]
    end
    _ctx = run User::Operation::Update do |result| 
      return redirect_to users_profile_path('id'=>params[:user][:id]), notice: "Profile updated successfully!"
    end
    @user   = _ctx["contract.default"] 
    @name  = "Editing #{_ctx[:model].name}"
    @email  = "Editing #{_ctx[:model].email}"
    @phone  = "Editing #{_ctx[:model].phone}"
    render :editProfile 
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.slim
= render 'layouts/navbar'
.form 
    .form-content 
        h2 Edit User

        = form_with model: @user, url: users_edit_path(:id => @user.id), method: :patch do |f|
            .content
                = f.hidden_field 'id'
                label Name
                span class="required-sign" * 
                = f.text_field 'name'
                - if @user.errors[:name].any?
                    .warning-message This #{ @user.errors[:name][0]}
            .content
                label Email
                span class="required-sign" * 
                = f.text_field 'email'
                - if @user.errors[:email].any?
                    .warning-message This #{ @user.errors[:email][0]}
            .content
                label Phone
                = f.text_field 'phone'
            .radio-group
                = f.radio_button :role, '1', class: 'radio-btn', checked: true
                label Admin
                = f.radio_button :role, '0', class: 'radio-btn'
                label Member
            .button-group
                = link_to "Back", users_show_path(:id=>@user.id), class: 'sub-btn'
                = f.submit 'Update', class: 'sub-btn'

app/views/users/editPassword.html.slim
= render 'layouts/navbar'
.form 
    .form-content 
        h2 Edit Password
        = form_with model: @user, url: users_editPassword_path(:id => @user.id), method: :patch do |f|
            .content
                = f.hidden_field 'id'
                label Password
                span class="required-sign" * 
                = f.password_field 'password'
                - if @user.errors[:password].any?
                    .warning-message This #{ @user.errors[:password][0]}
            .content
                label Password Confirm
                span class="required-sign" * 
                = f.password_field 'password_confirmation'
                - if @user.errors[:password_confirmation].any?
                    .warning-message This #{ @user.errors[:password_confirmation][0]}
            .button-group
                = link_to 'Back', users_profile_path( :id=>session[:id] ), class: 'sub-btn'
                = f.submit 'Update', class: 'sub-btn'

app/views/users/editProfile.html.slim
= render 'layouts/navbar'
.form 
    .form-content 
        h2 Edit User Profile

        = form_with model: @user, url: users_editProfile_path(:id => @user.id), method: :patch do |f|
            .content
                = f.hidden_field 'id'
                label Name
                span class="required-sign" * 
                = f.text_field 'name'
                - if @user.errors[:name].any?
                    .warning-message This #{ @user.errors[:name][0]}
            .content
                label Email
                span class="required-sign" * 
                = f.text_field 'email'
                - if @user.errors[:email].any?
                    .warning-message This #{ @user.errors[:email][0]}
            .content
                label Phone
                = f.text_field 'phone'
            .radio-group
                = f.radio_button :role, '1', class: 'radio-btn', checked: true
                label Admin
                = f.radio_button :role, '0', class: 'radio-btn'
                label Member
            .button-group
                = link_to 'Back', users_profile_path( :id=>session[:id] ), class: 'sub-btn'
                = f.submit 'Update', class: 'sub-btn'

app/views/users/index.html.slim
= render 'layouts/navbar'
.form
    .form-content
        .successMessage
            = flash.notice
        h2 All User
        = form_with  url: users_search_path,method: :get do
            .search-info
                = text_field_tag 'searchInfo', params[:searchInfo],placeholder: 'name , email, phone'
                .button-group
                = submit_tag 'Search', class: 'sub-btn'
        .create-btn
            = link_to "Create User", users_new_path, class: 'sub-btn'
        table 
            thead 
                tr 
                    th Name
                    th Email
                    th Role 
                    th Phone
                    th Action
            tbody
                - @users.each do |user|
                    tr 
                        td = user.name
                        td = user.email
                        td 
                            - if user.role == 1
                                p Admin
                            - else 
                                p Member
                        td = user.phone
                        td   
                            = link_to "Detail", users_show_path(:id=>user.id), class: 'sub-btn'
                            = link_to "Delete", users_destroy_path(:id=>user.id), class: 'sub-btn delete-btn', :data=>{ confirm: 'Are you sure you want to delete this post?' }
        .right-btn-group
            = will_paginate @users, renderer: BootstrapPagination::Rails


        

                

app/views/users/new.html.slim
= render 'layouts/navbar'
.form 
    .form-content
        .main-title
            h2 Add New User
        = form_with model: @form, url:users_new_path, method: :post do|f|
            .content 
                label Name
                span class="required-sign" * 
                = f.text_field 'name'
                - if @form.errors[:name].any?
                    .warning-message This #{ @form.errors[:name][0]}
            .content
                label Email
                span class="required-sign" * 
                = f.text_field 'email'
                - if @form.errors[:email].any?
                    .warning-message This #{ @form.errors[:email][0]}
            .content
                label Password
                span class="required-sign" * 
                = f.password_field 'password'
                - if @form.errors[:password].any?
                    .warning-message This #{ @form.errors[:password][0]}
            .content
                label Password Confirm
                span class="required-sign" * 
                = f.password_field 'password_confirmation'
                - if @form.errors[:password_confirmation].any?
                    .warning-message This #{ @form.errors[:password_confirmation][0]}
            .content
                label Phone
                = f.text_field 'phone'
            .content 
                .radio-group
                    = f.radio_button :role, '1', class: 'radio-btn', checked: true
                    label Admin
                    = f.radio_button :role, '0', class: 'radio-btn'
                    label Member
            .button-group
                = link_to "Back", users_list_path, class: 'sub-btn'
                = f.submit 'Add', class: 'sub-btn'

app/views/users/profile.html.slim
= render 'layouts/navbar'
.form 
    .form-content 
        .successMessage
            = flash.notice
        h2 User Profile
        .content
            label Name
            span class="required-sign" *
            = @user.name
        .content
            label Email
            span class="required-sign" * 
            = @user.email
        .content 
            label Password
            = link_to "Edit", users_editPassword_path(:id=>@user.id), class: 'sub-btn'
        .content
            label Phone  
            = @user.phone
        - if @user.role == 1
            label Admin
            i.fa.fa-user.user-awesome-icon
        - else 
            label Member
            i.fa.fa-user.user-awesome-icon
        .button-group
            = link_to "Back", users_list_path, class: 'sub-btn'
            = link_to "Edit", users_editProfile_path(:id=>@user.id), class: 'sub-btn'

app/views/users/show.html.slim
= render 'layouts/navbar'
.form 
    .form-content 
        .successMessage 
            = flash.notice
        h2 User Detail

        .content
            label Name
            span class="required-sign" * 
            = @user.name
        .content
            label Email
            span class="required-sign" * 
            = @user.email
        .content
            label Phone
            = @user.phone
        - if @user.role == 1
            label Admin
            i.fa.fa-user.user-awesome-icon
        - else 
            label Member
            i.fa.fa-user.user-awesome-icon
        .button-group
            = link_to "Back", users_list_path, class: 'sub-btn'
            = link_to 'Edit', users_edit_path(:id=>@user.id), class: 'sub-btn'