config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  patch 'posts/edit', to: 'posts#update'
  get 'posts/destroy'
  post 'posts/new', to: 'posts#create'
  post 'posts/store'
  get 'posts/search', to: 'posts#search_post'
  get 'posts/export', to: 'posts#export_csv'
  post 'posts/import', to: 'posts#import_csv'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'users/list', to: 'users#index'
  get 'users/new'
  post 'users/new', to: 'users#create'
  get 'users/search', to: 'users#search_user'
  get 'users/show'
  get 'users/destroy'
  get 'users/edit'
  patch 'users/edit', to: 'users#update'

  get 'users/profile'
  get 'users/editPassword'
  patch 'users/editPassword', to: 'users#updatePassword'
  get 'users/editProfile'
  patch 'users/editProfile', to: 'users#updateProfile'

  get 'password/reset'
  post 'password/reset' , to: 'password#create'
  get 'password/reset/edit', to: 'password#edit'
  patch 'password/reset/edit' , to: 'password#update'

  get 'login', to: 'login#login'
  post 'login', to: 'login#attempt_login'
  get 'logout', to: 'login#logout'
  
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :author, class_name: "User", foreign_key: "created_by"
    belongs_to :user, foreign_key: "created_by"

    # validates :title, presence: true ,length: { maximum: 255 }
    # validates :description, presence: true ,length: { maximum: 1000 }
    # validates :public_flag, presence: true

    def self.to_csv
        attributes = %w{title description public_flag created_by}
        CSV.generate(headers: true) do |csv|
            csv << attributes
            all.each do |post|
                csv << post.attributes.values_at(*attributes)
            end
        end
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_login

  def index
    run Post::Operation::Index do |result|
      @posts = result[:posts].paginate(:page=>params[:page],per_page: 5)
    end
  end

  def show
    run Post::Operation::Edit
    @post = result["model"]
  end

  def edit
    run Post::Operation::Edit
    @post = result["model"]
  end

  def new
    @form = Post.new
  end

  def create
    run Post::Operation::Create, current_user: current_user do |result|
      return redirect_to root_path,notice: "Post is saved successfully!"
    end
    render :new
  end

  def update
    if params[:post]
      puts (params[:post])
    else 
      params[:post] = params[:post_contract_update]
    end
    _ctx = run Post::Operation::Update, current_user: current_user  do |result|
      return redirect_to posts_show_path('id'=>params[:post][:id]), notice: "Post updated successfully!"
    end
    @post   = _ctx["contract.default"]
    @title  = "Editing #{_ctx[:model].title}"
    @description  = "Editing #{_ctx[:model].description}"
    render :edit
  end

  def destroy
    run Post::Operation::Destroy do |_|
      return redirect_to root_path, notice: "Post deleted successfully!"
    end 
  end

  def search_post
    @searchKey = params[:searchInfo]
    run Post::Operation::Search do |result|
      @posts = result[:posts].paginate(:page=>params[:page],per_page: 5)
      render :index
      return
    end
  end

  def export_csv
    run Post::Operation::Index do |result|
      @posts = result[:posts]
    end
    respond_to do |format|
      format.html
      format.csv {send_data @posts.to_csv, filename:"posts-#{Date.today}.csv"}
    end
  end

  def import_csv
    run Post::Operation::Import, current_user_id: current_user.id do |_|
      return redirect_to root_path,  notice: "CSV for posts is successfully uploaded."
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.slim
= render 'layouts/navbar'
.form 
    .form-content 
        h2 Edit Post

        = form_with model: @post, url: posts_edit_path(:id => @post.id), method: :patch do |f|
            .content
                = f.hidden_field 'id'
                label Post Title
                span class="required-sign" * 
                = f.text_field 'title'
                - if @post.errors[:title].any?
                    .warning-message This #{ @post.errors[:title][0]}
            .content
                label Description
                span class="required-sign" * 
                = f.text_area 'description', class: 'description-area'
                - if @post.errors[:description].any?
                    .warning-message This #{ @post.errors[:description][0]}
            .radio-group
                = f.radio_button :public_flag, '1', class: 'radio-btn', checked: true
                label Public
                = f.radio_button :public_flag, '0', class: 'radio-btn'
                label Private
            .button-group
                = link_to "Back", posts_show_path(:id=>@post.id), class: 'sub-btn'
                = f.submit 'Update', class: 'sub-btn'

app/views/posts/index.html.slim
= render 'layouts/navbar'
.form
    .form-content
        .successMessage
            = flash.notice
        h2 All Post
        .file-group 
            = form_tag posts_import_path, class: 'file-group', multipart: true do
                = file_field_tag 'file' , class: 'file-choose-box'
                .warning-message
                    = flash.alert
                = submit_tag 'CSV Import' , class: 'sub-btn file-choose-box'
                = link_to 'CSV Export', posts_export_path(format: :'csv'), class: 'sub-btn'
        = form_with  url: posts_search_path,method: :get do
            .search-info
                = text_field_tag 'searchInfo', params[:searchInfo],placeholder: 'title, description, author name'
                .button-group
                = submit_tag 'Search', class: 'sub-btn'

        .create-btn
            = link_to "Create Post", posts_new_path, class: 'sub-btn'
        - @posts.each do |post|
            .post-card
                .post-head
                    h4 = post.title
                    - if post.public_flag == 1
                        i.fa.fa-globe.awesome-icon
                    - else
                        i.fa.fa-lock.awesome-icon
                    p = 'Last updated on : ' + distance_of_time_in_words_to_now(post.updated_at) + ' ago'
                    p = 'Created by : ' + post.author.name
                .post-body
                    = post.description
                    .button-group
                        .post-btn-group
                            = link_to "Detail", posts_show_path(:id => post.id), class: 'sub-btn'
                            = link_to "Delete", posts_destroy_path(:id => post.id), class: 'sub-btn delete-btn',:data=>{ confirm: 'Are you sure you want to delete this post?' }
        .right-btn-group
            = will_paginate @posts, renderer: BootstrapPagination::Rails


        

                

app/views/posts/new.html.slim
= render 'layouts/navbar'
.form 
    .form-content
        .main-title
            h2 Add New Post
        = form_with model: @form, url:posts_new_path, method: :post do|f|
            .content 
                label Post Title
                span class="required-sign" * 
                = f.text_field 'title'
                - if @form.errors[:title].any?
                    .warning-message This #{ @form.errors[:title][0]}
            .content
                label Description
                span class="required-sign" * 
                = f.text_area 'description', class: 'description-area'
                - if @form.errors[:description].any?
                    .warning-message This #{ @form.errors[:description][0]}
            .content 
                .radio-group
                    = f.radio_button :public_flag, '1', class: 'radio-btn' , checked: true
                    label Public
                    = f.radio_button :public_flag, '0', class: 'radio-btn'
                    label Private
            .button-group
                = link_to "Back", posts_index_path, class: 'sub-btn'
                = f.submit 'Add', class: 'sub-btn'

app/views/posts/show.html.slim
= render 'layouts/navbar'
.form 
    .form-content 
        .successMessage 
            = flash.notice
        h2 Post Detail

        .content
            label Post Title
            span class="required-sign" * 
            = @post.title
        .content
            label Description
            span class="required-sign" * 
            = @post.description
        - if @post.public_flag == 1
            label Public
            i.fa.fa-globe.user-awesome-icon
        - else 
            label Private
            i.fa.fa-lock.user-awesome-icon
        .button-group
            = link_to "Back", posts_index_path, class: 'sub-btn'
            = link_to "Edit", posts_edit_path(:id=>@post.id), class: 'sub-btn'