config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts/index'
  get 'posts/show'
  get 'posts/new'
  get 'posts/edit'
  patch 'posts/edit', to: 'posts#update'
  get 'posts/destroy'
  post 'posts/new', to: 'posts#create'
  post 'posts/store'
  get 'posts/search', to: 'posts#search_post'
  get 'posts/export', to: 'posts#export_csv'
  post 'posts/import', to: 'posts#import_csv'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'users/list', to: 'users#index'
  get 'users/new'
  post 'users/new', to: 'users#create'
  get 'users/search', to: 'users#search_user'
  get 'users/show'
  get 'users/destroy'
  get 'users/edit'
  patch 'users/edit', to: 'users#update'

  get 'users/profile'
  get 'users/editPassword'
  patch 'users/editPassword', to: 'users#updatePassword'
  get 'users/editProfile'
  patch 'users/editProfile', to: 'users#updateProfile'

  get 'password/reset'
  post 'password/reset' , to: 'password#create'
  get 'password/reset/edit', to: 'password#edit'
  patch 'password/reset/edit' , to: 'password#update'

  get 'login', to: 'login#login'
  post 'login', to: 'login#attempt_login'
  get 'logout', to: 'login#logout'
  
end

app/views/layouts/_navbar.html.slim
nav 
    .nav-group
        a href="/" class="to__home"
            img src="/images/6592098_preview.png" class="blog-logo" alt=""/ 
        .navrow
            = link_to 'User List', users_list_path,class: is_active?(users_list_path) 
            .dropdown
                button class='dropbtn'
                    = session[:email]
                    i.fa.fa-caret-down
                .dropdown-content
                    = link_to 'User Profile', users_profile_path( :id=>session[:id] )
                    = link_to 'Logout', logout_path(:id=>session[:id])

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BulletinBorad</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> %>
    <link href="/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="/js/common.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>